########################## 生产环境 #########################

# 指定端口号
server:
  port: 80

spring:
  main:
    # 启动log
    log-startup-info: true


  application:
    name: TransactionManager
    # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/transactionManager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    ping-query: select * from dual
    maximum-active-connections: 10
    maximum-idle-connections: 5

  # 模板引擎
#  thymeleaf:
#    cache: true
#    check-template: true
#    check-template-location: true
#    prefix: classpath:/templates/
#    suffix: .html
  messages:
    # 指定语言不存在时，使用系统默认语言
    fallback-to-system-locale: true
    encoding: UTF-8
    basename: i18n.messages

# mybatis 配置文件
mybatis:
  type-aliases-package: com.spring.transaction.demo
  configuration:
    cache-enabled: true
    default-fetch-size: 100
    default-statement-timeout: 25
  # 配置Mapper.xml文件
  mapper-locations: classpath:/mapper/*.xml


# log 配置
logging:
  level:
   root: debug
   sample:
     mybatis:
       mapper: debug
  file:
    path: .
    name: transactionManager.log